"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { toast } from "sonner";

interface RoyaltyAgreementProps {
  isDisabled?: boolean;
}

export function RoyaltyAgreement({
  isDisabled = false,
}: RoyaltyAgreementProps) {
  const router = useRouter();
  const searchParams = useSearchParams();

  const handleNextClick = () => {
    const mainTab = searchParams.get("tab") || "deed-assignment";
    router.push(`?tab=${mainTab}&subTab=signatory`, { scroll: false });
  };

  const handlePreviousClick = () => {
    const mainTab = searchParams.get("tab") || "deed-assignment";
    router.push(`?tab=${mainTab}&subTab=deed`, { scroll: false });
  };

  return (
    <div className="space-y-8">
      <Card className="shadow-sm">
        <CardHeader className="bg-slate-50 rounded-t-lg">
          <CardTitle className="text-xl text-[#1B5E20]">
            Royalty Agreement
          </CardTitle>
          <CardDescription>
            Review the royalty agreement terms for your intellectual property
          </CardDescription>
        </CardHeader>
        <CardContent className="pt-6">
          <div className="space-y-6">
            <p className="text-sm mb-6">
              WHEREAS,{" "}
              <span className="font-bold">CARAGA STATE UNIVERSITY</span>, a
              Higher Education Institution with office address at Ampayon,
              Butuan City, represented by its President,
              <span className="font-bold"> ROLYN C. DAGUIL, Ph.D.</span>,
              hereinafter referred to as{" "}
              <span className="font-bold">Assignee</span>
            </p>

            <p className="text-sm">
              NOW, THEREFORE, <span className="font-bold">Assignors</span>{" "}
              hereby, by these presents do hereby assign and transfer unto said
              <span className="font-bold"> Assignee</span> the entire right,
              title and interest of said patent/utility model, the same to be
              held and enjoyed by <span className="font-bold">Assignee</span>{" "}
              hereof for the full term of protection granted by law,
              substantially made, as fully and entirely as the same would have
              been held by the <span className="font-bold">Assignors</span>
              had this assignment and transfer not been made.
            </p>

            <p className="text-sm">Additionally, it is hereby agreed that:</p>

            <div className="space-y-4 pl-6">
              <p className="text-sm">
                a. The <span className="font-bold">Assignors</span> shall be
                entitled to a royalty share, per Section 7(d)(i) of the CSU IP
                Policy and Section 7(c)(iv) under (DO No. 003, s. 2018), from
                the net income generated by the commercialization, licensing, or
                other revenue-generating activities related to the said
                patent/utility model carried out by the{" "}
                <span className="font-bold">Assignee</span>.
              </p>

              <p className="text-sm">
                b. The <span className="font-bold">Assignors'</span> right to
                the royalty share is contingent upon the successful
                commercialization or revenue generation resulting from the said
                patent/utility model. In the event that there is no income
                generated, no royalty shall be paid.
              </p>

              <p className="text-sm">
                c. The benefits and royalties outlined in this Agreement shall
                continue even after the
                <span className="font-bold"> Assignors</span> graduates from the{" "}
                <span className="font-bold">Assignee</span>, provided that the
                said patent/utility model continues to generate income or
                revenue.
              </p>

              <p className="text-sm">
                d. Regardless of any other provision in this agreement, after
                the expiration of the patent/utility model right, no further
                royalty shall be payable to the{" "}
                <span className="font-bold">Assignors</span>. However, the{" "}
                <span className="font-bold">Assignee</span> shall continue to
                have the right to exploit or use of the said patent/utility
                model of the <span className="font-bold">Assignee</span>.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      <Separator className="my-6" />

      <div className="flex justify-between items-center">
        <div className="flex gap-4">
          <Button
            type="button"
            onClick={handlePreviousClick}
            variant="outline"
            disabled={isDisabled}
            className="bg-green-50 text-green-700 hover:bg-green-100"
          >
            Previous
          </Button>
        </div>

        <div className="flex gap-4">
          <Button
            type="button"
            onClick={handleNextClick}
            disabled={isDisabled}
            className="bg-green-700 text-white hover:bg-green-800"
          >
            Next
          </Button>
        </div>
      </div>
    </div>
  );
}
