import { ProjectDocument } from "@/app/(admin)/admin/client-proj-dash/types";

export const MOCK_DOCUMENTS: ProjectDocument[] = [
  // Forms
  {
    id: "form-1",
    title: "IP Disclosure Form",
    type: "form",
    category: "forms",
    uploadedAt: "2024-02-15T08:30:00Z",
    uploadedBy: "John Doe",
    fileUrl: "/documents/ip-disclosure.pdf",
    status: "verified",
    requiresValidation: true,
    validatedBy: "Admin User",
    validatedAt: "2024-02-16T10:15:00Z",
    remarks: "All requirements met. Approved for processing.",
  },
  {
    id: "form-2",
    title: "Patent Application Form",
    type: "form",
    category: "forms",
    uploadedAt: "2024-02-14T09:45:00Z",
    uploadedBy: "Jane Smith",
    fileUrl: "/documents/patent-application.pdf",
    status: "processing",
    requiresValidation: true,
    remarks: "Under review by the patent committee",
  },
  {
    id: "form-3",
    title: "Certification Request",
    type: "form",
    category: "forms",
    uploadedAt: "2024-02-13T14:20:00Z",
    uploadedBy: "John Doe",
    fileUrl: "/documents/certification.pdf",
    status: "not_verified",
    requiresValidation: true,
  },

  // Attachments
  {
    id: "attach-1",
    title: "Technical Documentation",
    type: "report",
    category: "attachments",
    uploadedAt: "2024-02-12T11:00:00Z",
    uploadedBy: "Sarah Johnson",
    fileUrl: "/documents/tech-doc.pdf",
    status: "verified",
    requiresValidation: false,
  },
  {
    id: "attach-2",
    title: "Research Findings",
    type: "report",
    category: "attachments",
    uploadedAt: "2024-02-11T15:30:00Z",
    uploadedBy: "Mike Wilson",
    fileUrl: "/documents/research.pdf",
    status: "not_verified",
    requiresValidation: false,
  },
  {
    id: "attach-3",
    title: "Prototype Photos",
    type: "application",
    category: "attachments",
    uploadedAt: "2024-02-10T13:45:00Z",
    uploadedBy: "Jane Smith",
    fileUrl: "/documents/photos.zip",
    status: "verified",
    requiresValidation: false,
  },

  // Requirements
  {
    id: "req-1",
    title: "Ethics Committee Approval",
    type: "contract",
    category: "requirements",
    uploadedAt: "2024-02-09T10:20:00Z",
    uploadedBy: "John Doe",
    fileUrl: "/documents/ethics-approval.pdf",
    status: "verified",
    requiresValidation: true,
    validatedBy: "Ethics Committee",
    validatedAt: "2024-02-10T09:00:00Z",
    remarks: "Approved with minor revisions",
  },
  {
    id: "req-2",
    title: "Prior Art Search Results",
    type: "report",
    category: "requirements",
    uploadedAt: "2024-02-08T16:15:00Z",
    uploadedBy: "Sarah Johnson",
    fileUrl: "/documents/prior-art.pdf",
    status: "processing",
    requiresValidation: true,
    remarks: "Pending review by patent examiner",
  },
  {
    id: "req-3",
    title: "Inventor Declaration",
    type: "contract",
    category: "requirements",
    uploadedAt: "2024-02-07T14:30:00Z",
    uploadedBy: "Mike Wilson",
    fileUrl: "/documents/declaration.pdf",
    status: "not_verified",
    requiresValidation: true,
  },
];